//
// Created by qijiabao on 1/6/2024.
//
/*************************************************************************
 * @Project:     paper_analysis
 * @File:        Document.cpp
 * @Brief:       Brief description of the file
 * @Author:      qijiabao
 * @Contact:     Your Contact Information (e.g., email)
 * @Date:        1/6/2024
 * @Description: 
 *               This file is generated by CLion to provide a
 *               template for C/C++ source or header files. You can modify
 *               this template according to your project's needs.
 * @Note:        Additional notes or important points related to the file.
 * @License:     License information if applicable.
 * @Version:     Version number or other version information.
 * @TODO:        List of tasks or things to be done in the file (if any).
 * @Bug:         List of known issues or bugs (if any).
 * @IDE:         CLion
 ************************************************************************/
// Include necessary headers, if any

// Additional comments or code go here#include "Document.h"

#include "Document.h"

#include <algorithm>
#include <cctype>
#include <iostream>
#include <xercesc/dom/DOMAttr.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMImplementation.hpp>
#include <xercesc/dom/DOMImplementationLS.hpp>
#include <xercesc/dom/DOMImplementationRegistry.hpp>
#include <xercesc/dom/DOMNamedNodeMap.hpp>
#include <xercesc/dom/DOMNode.hpp>
#include <xercesc/dom/DOMNodeList.hpp>

#include "CommandParser.h"
#include "Paragraph.h"
#include "Run.h"
#include "StringExtractor.h"
#include "XMLParserFactory.h"


namespace qi {
Document::Document()
{
  // 创建 XMLParserFactory 对象并构建 DOM 解析器
  XMLParserFactory::createDOMParser("setting01", &documentParser_);
}
Document::~Document()
{
  // 释放解析器
  documentParser_->release();
}
// 打开文档
ErrorCode::ErrorCodeEnum Document::openDocument(const std::string &documentFilePath)
{
  // 保存文档路径
  documentPath_ = documentFilePath;
  // 保存文档名称
  documentName_ = documentFilePath.substr(documentFilePath.find_last_of('/') + 1);
  // 检查文档路径是否为空
  if (documentFilePath.empty())
  {
    std::cerr << "Document path is empty!" << std::endl;
    return qi::ErrorCode::ErrorCodeEnum::FAILED;
  }
  // 解析 XML 文件并获取文档
  document_ = documentParser_->parseURI(documentFilePath.c_str());
  // 检查文档是否为空
  if (document_ == nullptr)
  {
    std::cerr << "Document is empty!" << std::endl;
    return qi::ErrorCode::ErrorCodeEnum::FAILED;
  }
  // 获取文档的所有<w:p>标签
  paragraphs_.paragraphsParser(document_);

  // 打印出所有段落中的文本
  XMLSize_t paragraphCount = 0;
  paragraphs_.getParagraphCount(&paragraphCount);
  for (XMLSize_t i = 0; i < paragraphCount; ++i)
  {
    Run runs(&paragraphs_);
    XMLSize_t runCount = 0;
    runs.getRunCount(&runCount);
    for (XMLSize_t j = 0; j < runCount; ++j)
    {
      XERCES_CPP_NAMESPACE::DOMNode *run = nullptr;
      runs.getRun(&run);
      std::string text;
      runs.getRunText(&text);
      // 使用标准库的算法和迭代器去除空白字符
      text.erase(
              std::remove_if(text.begin(), text.end(), ::isspace),
              text.end());
      std::cout << text << std::endl;
      runs.getNextRun(&run);
    }
    paragraphs_.nextParagraph();
  }

  return qi::ErrorCode::ErrorCodeEnum::SUCCESS;
}

}// namespace qi