//
// Created by qijiabao on 1/6/2024.
//
/*************************************************************************
 * @Project:     paper_analysis
 * @File:        main.cpp
 * @Brief:       Brief description of the file
 * @Author:      qijiabao
 * @Contact:     Your Contact Information (e.g., email)
 * @Date:        1/6/2024
 * @Description: 
 *               This file is generated by CLion to provide a
 *               template for C/C++ source or header files. You can modify
 *               this template according to your project's needs.
 * @Note:        Additional notes or important points related to the file.
 * @License:     License information if applicable.
 * @Version:     Version number or other version information.
 * @TODO:        List of tasks or things to be done in the file (if any).
 * @Bug:         List of known issues or bugs (if any).
 * @IDE:         CLion
 ************************************************************************/
// Include necessary headers, if any

// Additional comments or code go here

#include <iostream>

#include <xercesc/util/PlatformUtils.hpp>
#include "Document.h"

int main()
{
  // 初始化 Xerces-C++
  XERCES_CPP_NAMESPACE::XMLPlatformUtils::Initialize();
  {
    qi::Document document;
    document.Open("D:\\WorkSpace\\VSCodeFile\\word\\Template02\\word\\document.xml");
    std::vector<qi::ParagraphBlock> paragraphBlockVector;
    document.getParagraphVetor(paragraphBlockVector);
  }
  // 释放 Xerces-C++
  XERCES_CPP_NAMESPACE::XMLPlatformUtils::Terminate();
  return 0;
}
