//
// Created by qijiabao on 2/2/2024.
//
/*************************************************************************
 * @Project:     paper_analysis
 * @File:        EraseSpaces.cpp
 * @Brief:       Brief description of the file
 * @Author:      qijiabao
 * @Contact:     Your Contact Information (e.g., email)
 * @Date:        2/2/2024
 * @Description: 
 *               This file is generated by CLion to provide a
 *               template for C/C++ source or header files. You can modify
 *               this template according to your project's needs.
 * @Note:        Additional notes or important points related to the file.
 * @License:     License information if applicable.
 * @Version:     Version number or other version information.
 * @TODO:        List of tasks or things to be done in the file (if any).
 * @Bug:         List of known issues or bugs (if any).
 * @IDE:         CLion
 ************************************************************************/
// Include necessary headers, if any

// Additional comments or code go here
#include "EraseSpaces.h"

#include <algorithm>
#include <cctype>
#include <iostream>

namespace qi {
ErrorCode::ErrorCodeEnum qi::EraseSpaces::eraseSpaces(std::string &str)
{
  if (str.empty())
  {
    return ErrorCode::ErrorCodeEnum::SUCCESS;
  }
  // 删除字符串中的空格
  str.erase(std::remove(str.begin(), str.end(), ' '), str.end());

  return ErrorCode::ErrorCodeEnum::SUCCESS;
}
ErrorCode::ErrorCodeEnum EraseSpaces::eraseNewLine(std::string &str)
{
  if (str.empty())
  {
    return ErrorCode::ErrorCodeEnum::SUCCESS;
  }
  // 删除字符串中的换行
  str.erase(std::remove(str.begin(), str.end(), '\n'), str.end());

  return ErrorCode::ErrorCodeEnum::SUCCESS;
}
}// namespace qi