//
// Created by qijiabao on 1/7/2024.
//
/*************************************************************************
 * @Project:     paper_analysis
 * @File:        CommandParser.h
 * @Brief:       Brief description of the file
 * @Author:      qijiabao
 * @Contact:     Your Contact Information (e.g., email)
 * @Date:        1/7/2024
 * @Description: 
 *               This file is generated by CLion to provide a
 *               template for C/C++ source or header files. You can modify
 *               this template according to your project's needs.
 * @Note:        Additional notes or important points related to the file.
 * @License:     License information if applicable.
 * @Version:     Version number or other version information.
 * @TODO:        List of tasks or things to be done in the file (if any).
 * @Bug:         List of known issues or bugs (if any).
 * @IDE:         CLion
 ************************************************************************/
// Include necessary headers, if any

// Additional comments or code go here
#ifndef PAPER_ANALYSIS_COMMANDPARSER_H
#define PAPER_ANALYSIS_COMMANDPARSER_H

#include <string>
#include <unordered_map>
#include <vector>

class CommandParser {
private:
  // 命令映射关系
  std::unordered_map<std::string, std::string> commandMap_;
  // 解析结果
  std::string result_;
public:
  CommandParser();
  ~CommandParser();
  // 解析命令字符串
  std::string parseCommand(const std::string& commandString);

private:
  // 处理命令
  void processCommand(const std::string& command);
};


#endif//PAPER_ANALYSIS_COMMANDPARSER_H
