//
// Created by qijiabao on 1/7/2024.
//
/*************************************************************************
 * @Project:     paper_analysis
 * @File:        main.cpp
 * @Brief:       Brief description of the file
 * @Author:      qijiabao
 * @Contact:     Your Contact Information (e.g., email)
 * @Date:        1/7/2024
 * @Description: 
 *               This file is generated by CLion to provide a
 *               template for C/C++ source or header files. You can modify
 *               this template according to your project's needs.
 * @Note:        Additional notes or important points related to the file.
 * @License:     License information if applicable.
 * @Version:     Version number or other version information.
 * @TODO:        List of tasks or things to be done in the file (if any).
 * @Bug:         List of known issues or bugs (if any).
 * @IDE:         CLion
 ************************************************************************/
// Include necessary headers, if any

// Additional comments or code go here

#include "XMLParser.h"
#include <iostream>

int main() {
    const char* xmlFilePath = "D:\\WorkSpace\\VSCodeFile\\word\\Test06\\word\\document.xml";

    qi::XMLParser xmlParser;

    if (xmlParser.loadXMLFile(xmlFilePath)) {
        std::cout << "XML parsing successful." << std::endl;
        std::cout << "Printing XML content:" << std::endl;
        xmlParser.parseXMLTree();
    } else {
        std::cerr << "XML parsing failed." << std::endl;
    }

    return 0;
}
