//
// Created by qijiabao on 1/7/2024.
//
/*************************************************************************
 * @Project:     paper_analysis
 * @File:        XMLParser.h
 * @Brief:       Brief description of the file
 * @Author:      qijiabao
 * @Contact:     Your Contact Information (e.g., email)
 * @Date:        1/7/2024
 * @Description: 
 *               This file is generated by CLion to provide a
 *               template for C/C++ source or header files. You can modify
 *               this template according to your project's needs.
 * @Note:        Additional notes or important points related to the file.
 * @License:     License information if applicable.
 * @Version:     Version number or other version information.
 * @TODO:        List of tasks or things to be done in the file (if any).
 * @Bug:         List of known issues or bugs (if any).
 * @IDE:         CLion
 ************************************************************************/
// Include necessary headers, if any

// Additional comments or code go here
#ifndef PAPER_ANALYSIS_XMLPARSER_H
#define PAPER_ANALYSIS_XMLPARSER_H

#include <xercesc/parsers/XercesDOMParser.hpp>
#include <xercesc/dom/DOMLSParser.hpp>
#include <xercesc/dom/DOMElement.hpp>

namespace qi {

class XMLParser {
public:
  XMLParser();
  ~XMLParser();

  bool loadXMLFile(char const* file_path);
  bool getDOMElementPtr(XERCES_CPP_NAMESPACE::DOMElement** root);
  // 解析为xml树
  bool parseXMLTree();


private:
  XERCES_CPP_NAMESPACE::DOMLSParser* parser_ = nullptr;
  XERCES_CPP_NAMESPACE::ErrorHandler* errHandler_ = nullptr;
  XERCES_CPP_NAMESPACE:: DOMDocument* doc_ = nullptr;
  XERCES_CPP_NAMESPACE::DOMElement* root_ = nullptr;
};

}// namespace qi

#endif//PAPER_ANALYSIS_XMLPARSER_H
