//
// Created by qijiabao on 1/6/2024.
//
/*************************************************************************
 * @Project:     paper_analysis
 * @File:        Document.h
 * @Brief:       Brief description of the file
 * @Author:      qijiabao
 * @Contact:     Your Contact Information (e.g., email)
 * @Date:        1/6/2024
 * @Description: 
 *               This file is generated by CLion to provide a
 *               template for C/C++ source or header files. You can modify
 *               this template according to your project's needs.
 * @Note:        Additional notes or important points related to the file.
 * @License:     License information if applicable.
 * @Version:     Version number or other version information.
 * @TODO:        List of tasks or things to be done in the file (if any).
 * @Bug:         List of known issues or bugs (if any).
 * @IDE:         CLion
 ************************************************************************/
// Include necessary headers, if any

// Additional comments or code go here#ifndef PAPER_ANALYSIS_DOCUMENT_H
#ifndef PAPER_ANALYSIS_DOCUMENT_H
#define PAPER_ANALYSIS_DOCUMENT_H

#include <string>

#include <xercesc/dom/DOMElement.hpp>
#include <xercesc/dom/DOMLSParser.hpp>

#include "ErrorCode.h"
#include "Paragraph.h"
#include "Run.h"
//#include "Section.h
#include "Style.h"
#include "Template.h"

namespace qi {

class Document {
private:
  // DOM 解析器
  XERCES_CPP_NAMESPACE::DOMLSParser* documentParser_;
  // 文档
  XERCES_CPP_NAMESPACE::DOMDocument* document_;
  // 文档路径
  std::string documentPath_;
  // 文档名称
  std::string documentName_;
  // <w:p> 段落
  Paragraph paragraphs_;
  // <w:r> 运行块
  Run runs_;
  // <w:sectPr> 节属性
  // Section section_;
  // <w:style> 样式
  Style styles_;
  // 模板信息
  Template documentTemplate_;

public:
  Document();
  ~Document();
  // open document
  ErrorCode::ErrorCodeEnum openDocument(const std::string& path);

};

}// namespace qi

#endif//PAPER_ANALYSIS_DOCUMENT_H
