//
// Created by qijiabao on 2/2/2024.
//
/*************************************************************************
 * @Project:     paper_analysis
 * @File:        EraseSpaces.h
 * @Brief:       Brief description of the file
 * @Author:      qijiabao
 * @Contact:     Your Contact Information (e.g., email)
 * @Date:        2/2/2024
 * @Description: 
 *               This file is generated by CLion to provide a
 *               template for C/C++ source or header files. You can modify
 *               this template according to your project's needs.
 * @Note:        Additional notes or important points related to the file.
 * @License:     License information if applicable.
 * @Version:     Version number or other version information.
 * @TODO:        List of tasks or things to be done in the file (if any).
 * @Bug:         List of known issues or bugs (if any).
 * @IDE:         CLion
 ************************************************************************/
// Include necessary headers, if any

// Additional comments or code go here
#ifndef PAPER_ANALYSIS_ERASESPACES_H
#define PAPER_ANALYSIS_ERASESPACES_H

#include <string>

#include "ErrorCode.h"

namespace qi {

class EraseSpaces {
public:
  // 删除字符串中的空格
  ErrorCode::ErrorCodeEnum eraseSpaces(std::string &str);
  // 删除字符串中的换行
  ErrorCode::ErrorCodeEnum eraseNewLine(std::string &str);
};

}// namespace qi

#endif//PAPER_ANALYSIS_ERASESPACES_H
