//
// Created by qijiabao on 2/2/2024.
//
/*************************************************************************
 * @Project:     paper_analysis
 * @File:        NodeToElement.h
 * @Brief:       Brief description of the file
 * @Author:      qijiabao
 * @Contact:     Your Contact Information (e.g., email)
 * @Date:        2/2/2024
 * @Description: 
 *               This file is generated by CLion to provide a
 *               template for C/C++ source or header files. You can modify
 *               this template according to your project's needs.
 * @Note:        Additional notes or important points related to the file.
 * @License:     License information if applicable.
 * @Version:     Version number or other version information.
 * @TODO:        List of tasks or things to be done in the file (if any).
 * @Bug:         List of known issues or bugs (if any).
 * @IDE:         CLion
 ************************************************************************/
// Include necessary headers, if any

// Additional comments or code go here
#ifndef PAPER_ANALYSIS_NODETOELEMENT_H
#define PAPER_ANALYSIS_NODETOELEMENT_H

#include <xercesc/dom/DOMElement.hpp>
#include <xercesc/dom/DOMNode.hpp>

#include "ErrorCode.h"

namespace qi {

class NodeToElement {
public:
  NodeToElement() = default;
  ~NodeToElement() = default;
  // 节点转换为元素
  ErrorCode::ErrorCodeEnum nodeToElement(XERCES_CPP_NAMESPACE::DOMNode* node, XERCES_CPP_NAMESPACE::DOMElement** element);
};

}// namespace qi

#endif//PAPER_ANALYSIS_NODETOELEMENT_H
