//
// Created by qijiabao on 2/2/2024.
//
/*************************************************************************
 * @Project:     paper_analysis
 * @File:        main.cpp
 * @Brief:       Brief description of the file
 * @Author:      qijiabao
 * @Contact:     Your Contact Information (e.g., email)
 * @Date:        2/2/2024
 * @Description: 
 *               This file is generated by CLion to provide a
 *               template for C/C++ source or header files. You can modify
 *               this template according to your project's needs.
 * @Note:        Additional notes or important points related to the file.
 * @License:     License information if applicable.
 * @Version:     Version number or other version information.
 * @TODO:        List of tasks or things to be done in the file (if any).
 * @Bug:         List of known issues or bugs (if any).
 * @IDE:         CLion
 ************************************************************************/
// Include necessary headers, if any

// Additional comments or code go here

#include <iostream>
#include <string>
#include <codecvt>
#include <locale>
#include <cuchar>

int main() {
    // 定义包含 UTF-8 编码文本的字节串
    const char bytes[] = "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\261\317\302\333\316\304\324\255\264\264\320\324\311\371\303\367\n\n\n";

    // 检测编码类型
    std::string_view byte_view(bytes);
    std::wstring_convert<std::codecvt_utf8_utf16<char16_t>, char16_t> converter;
    std::u16string utf16_text = converter.from_bytes(byte_view.data());

    // 打印检测到的编码类型
    std::cout << "Detected encoding: UTF-16" << std::endl;

    // 将字节串解码为 UTF-8 编码的字符串
    std::wstring_convert<std::codecvt_utf8<char16_t>, char16_t> utf8_converter;
    std::string utf8_text = utf8_converter.to_bytes(utf16_text);

    // 打印解码后的字符串
    std::cout << "Decoded text: " << utf8_text << std::endl;

    return 0;
}
