//
// Created by qijiabao on 1/6/2024.
//
/*************************************************************************
 * @Project:     paper_analysis
 * @File:        Document.h
 * @Brief:       Brief description of the file
 * @Author:      qijiabao
 * @Contact:     Your Contact Information (e.g., email)
 * @Date:        1/6/2024
 * @Description: 
 *               This file is generated by CLion to provide a
 *               template for C/C++ source or header files. You can modify
 *               this template according to your project's needs.
 * @Note:        Additional notes or important points related to the file.
 * @License:     License information if applicable.
 * @Version:     Version number or other version information.
 * @TODO:        List of tasks or things to be done in the file (if any).
 * @Bug:         List of known issues or bugs (if any).
 * @IDE:         CLion
 ************************************************************************/
// Include necessary headers, if any

// Additional comments or code go here#ifndef PAPER_ANALYSIS_DOCUMENT_H
#ifndef PAPER_ANALYSIS_DOCUMENT_H
#define PAPER_ANALYSIS_DOCUMENT_H

#include <string>
#include <vector>
#include <xercesc/dom/DOMElement.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>

#include "Paragraph.h"
#include "Template.h"
#include "ErrorCode.h"

namespace qi {

// 段落块信息
struct ParagraphBlock {
  // 段落标记字
  std::string ParagraphKey = "null";
  // 段落块集合
  std::vector<Paragraph> ParagraphsVector;
};

class Document {
private:
  // DOM 解析器
  XERCES_CPP_NAMESPACE::XercesDOMParser parser_;
  // 文档
  XERCES_CPP_NAMESPACE::DOMDocument* document_;

  // 模板信息
  Template documentTemplate_;
  // 段落块集合
  std::vector<ParagraphBlock> paragraphBlockVector_;

public:
  Document();
  ~Document();
  // open document
  ErrorCode::ErrorCodeEnum Open(const std::string& path);
  // get paragraphvector
  ErrorCode::ErrorCodeEnum getParagraphVetor( std::vector<ParagraphBlock>& paragraphBlockVector);
  // get section
  // Section getSection();
  // get table
  // Table getTable();
  // get document information
  // ??? getDocumentInfo();
};

}// namespace qi

#endif//PAPER_ANALYSIS_DOCUMENT_H
