//
// Created by qijiabao on 1/6/2024.
//
/*************************************************************************
 * @Project:     paper_analysis
 * @File:        Template.cpp
 * @Brief:       Brief description of the file
 * @Author:      qijiabao
 * @Contact:     Your Contact Information (e.g., email)
 * @Date:        1/6/2024
 * @Description: 
 *               This file is generated by CLion to provide a
 *               template for C/C++ source or header files. You can modify
 *               this template according to your project's needs.
 * @Note:        Additional notes or important points related to the file.
 * @License:     License information if applicable.
 * @Version:     Version number or other version information.
 * @TODO:        List of tasks or things to be done in the file (if any).
 * @Bug:         List of known issues or bugs (if any).
 * @IDE:         CLion
 ************************************************************************/
// Include necessary headers, if any

// Additional comments or code go here#include "Template.h"

#include "Template.h"

namespace qi {
std::vector<TemplateBlock> qi::Template::getTemplateBlock()
{
  return templateBlockVector_;
}
bool Template::addTemplateBlock(const TemplateBlock &templateBlock)
{
  templateBlockVector_.push_back(templateBlock);
  return true;
}
bool Template::clearTemplateBlock()
{
  templateBlockVector_.clear();
  return true;
}
}// namespace qi